### ISSUE TITLE
server CTD

### ISSUE THREAD

**Issue by Sty2k5** [Mrthomas20121/TinkerFirmaCraft#2] opened 2019-12-03 03:41 UTC
**Describe the bug**
The mod when installed on a server crashes the server, it appears to reference slimeknight's library which for some reason doesn't work.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
 - Minecraft: [e.g. 1.12] 1.12.2 
 - TinkerFirmaCraft [e.g. 0.0.1] 1.02
 - Forge [e.g. 14.23.5.2847] most recent

**Additional context**

**Comment by Mrthomas20121** [comment] 2019-12-04 06:56
I am unable to reproduce the crash on a server, can you send the log/crash report?

**Comment by Sty2k5** [comment] 2019-12-04 20:19
[crash-2019-12-02_06.28.46-server.txt](https://github.com/Mrthomas20121/TinkerFirmaCraft/files/3923777/crash-2019-12-02_06.28.46-server.txt)

**Comment by Mrthomas20121** [comment] 2019-12-06 14:50
Will fix it for the next release.

**Comment by Mrthomas20121** [comment] 2019-12-09 11:44
Fixed in 1.0.3. Should be up on curseforge tomorrow

**Closed as completed by Mrthomas20121** 2019-12-09 11:44 UTC
Labels: bug, Fixed in dev
